DROP TABLE MEMBER ;
DROP TABLE BOARD;
DROP TABLE PROJECT;
DROP TABLE PAYMENT;
DROP TABLE GETPROJECT;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE SETPAY;


CREATE TABLE MEMBER(
        MEMAIL VARCHAR2(80) PRIMARY KEY,
        MIMAGE VARCHAR2(20) DEFAULT 'noimg.png',
        MNAME VARCHAR2(40) NOT NULL,
        MPW VARCHAR2(20) NOT NULL,
        MJDATE DATE DEFAULT SYSDATE,
        MLOC VARCHAR2(20),
        MSELF VARCHAR2(100),
        MPHONE1 VARCHAR2(6),
        MPHONE2 VARCHAR2(6),
        MPHONE3 VARCHAR2(6),
       
);

CREATE TABLE PROJECT(
    PNO NUMBER(38) PRIMARY KEY,
    PTITLE VARCHAR2(20) NOT NULL,
    MEMAIL VARCHAR2(80) REFERENCES MEMBER(MEMAIL) NOT NULL,
    PDATE DATE NOT NULL,
    PPAY NUMBER(38) NOT NULL,
    PNOW NUMBER(38) DEFAULT 0,
    PCNT NUMBER(38) DEFAULT 0,
    PCONTENT CLOB,
    PIMAGE VARCHAR2(100),
    PCATEGORY VARCHAR2(100) NOT NULL,
    PACCOUNT VARCHAR2(100) NOT NULL,
    PBANKNAME VARCHAR2(100) NOT NULL,
    PACNAME VARCHAR(20) NOT NULL
);
SELECT COUNT(*) FROM PROJECT P,(SELECT G.PNO FROM MEMBER M , GETPROJECT G WHERE M.MEMAIL = G.MEMAIL AND G.MEMAIL=? ORDER BY PNO) A WHERE A.PNO = P.PNO;

SELECT P.*,a.PAY FROM PROJECT P,(SELECT ROWNUM RN, G.PNO,G.PAY FROM MEMBER M , GETPROJECT G WHERE M.MEMAIL = G.MEMAIL AND G.MEMAIL='test@test' ORDER BY PNO) A WHERE A.PNO = P.PNO AND RN BETWEEN 1 AND 3;

(SELECT G.PNO FROM MEMBER M , GETPROJECT G WHERE M.MEMAIL = G.MEMAIL AND G.MEMAIL='test@test');
CREATE TABLE GETPROJECT(
    GNO NUMBER(38) PRIMARY KEY,
    MEMAIL VARCHAR2(80) NOT NULL REFERENCES MEMBER(MEMAIL),
    PNO NUMBER(38) NOT NULL REFERENCES PROJECT(PNO),
    PAY NUMBER(38) NOT NULL
);
CREATE SEQUENCE GETPROJECT_SEQ
START WITH 1
MAXVALUE 99999999
NOCACHE
NOCYCLE;

CREATE TABLE PAYMENT(
    PCNUM VARCHAR2(20) PRIMARY KEY,
    PMONTH VARCHAR2(2) NOT NULL,
    PYEAR VARCHAR2(2) NOT NULL,
    PBIRTH VARCHAR2(6) NOT NULL,
    PPW VARCHAR2(2) NOT NULL,
    PPHONE1 VARCHAR2(4) NOT NULL,
    PPHONE2 VARCHAR2(4) NOT NULL,
    PPHONE3 VARCHAR2(4) NOT NULL,
    MEMAIL VARCHAR2(80) REFERENCES MEMBER(MEMAIL) NOT NULL
);

CREATE TABLE BOARD(
    BNO NUMBER(38) PRIMARY KEY,
    MEMAIL VARCHAR2(80) REFERENCES MEMBER(MEMAIL) NOT NULL,
    BTITLE VARCHAR2(40) NOT NULL,
    BCONTENT VARCHAR2(1000) NOT NULL,
    BIMAGE VARCHAR(100),
    BGROUP NUMBER(38) NOT NULL,
    BSTEP NUMBER(9) DEFAULT 0,
    BINDENT NUMBER(2) DEFAULT 0,
    BDATE DATE DEFAULT SYSDATE,
    BHIT NUMBER(38) DEFAULT 0,
    BIP VARCHAR2(20)
);
CREATE SEQUENCE BOARD_SEQ
START WITH 1
MAXVALUE 99999999
NOCACHE
NOCYCLE;

CREATE TABLE PBOARD(
    PBNO NUMBER(38) PRIMARY KEY,
    MEMAIL VARCHAR2(80) NOT NULL,
    PBCONTENT VARCHAR2(1000) NOT NULL,
    PBSTEP NUMBER(9) NOT NULL,
    PNO NUMBER(38) REFERENCES PROJECT(PNO),
    PBDATE DATE DEFAULT SYSDATE,
    PBGROUP NUMBER(38) NOT NULL,
    PBSTEP NUMBER(9) NOT NULL,
    PBIP VARCHAR2(20)
);

CREATE TABLE SETPAY(
    SPNO NUMBER(38) PRIMARY KEY,
    PNO NUMBER(38) NOT NULL REFERENCES PROJECT(PNO),
    PNAME VARCHAR2(100) NOT NULL,
    PAY NUMBER(38) NOT NULL,
    PEXP VARCHAR2(1000) NOT NULL
);
CREATE SEQUENCE SETPAY_SEQ
START WITH 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;

CREATE TABLE ADMIN(
    AID VARCHAR2(20) PRIMARY KEY,
    APW VARCHAR2(20) NOT NULL
);

CREATE TABLE NOTICE(
    NNO NUMBER(38) PRIMARY KEY,
    AID VARCHAR2(20) REFERENCES ADMIN(AID) NOT NULL,
    NTITLE VARCHAR2(20) NOT NULL,
    NCONTENT VARCHAR2(1000),
    NIMAGE VARCHAR2(100),
    NIMAGE2 VARCHAR2(100),
    NIMAGE3 VARCHAR2(100),
    NDATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE PROJECT_SEQ
START WITH 1
MAXVALUE 9999999
NOCYCLE
NOCACHE;

SELECT * FROM MEMBER WHERE MEMAIL = 'test@test' AND MPW='111';
--ȸ���˻�
SELECT * FROM MEMBER WHERE MEMAIL='test@test';
--ȸ������
INSERT INTO MEMBER (MEMAIL,MNAME,MPW) VALUES(?,?,?);
--ȸ����������
UPDATE MEMBER SET MNAME = ?,MLOC= ?,MIMAGE = ?,MSELF= ?,MPHONE1= ?,MPHONE2= ?,MPHONE3= ? WHERE MEMAIL= ?;
--�α���
SELECT * FROM MEMBER WHERE MEMAIL = ? AND MPW=?;
--ȸ�������Ͱ�������
SELECT * FROM MEMBER WHERE MEMAIL = ?;
--��ü�˻�
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM MEMBER ORDER BY MNAME)A) WHERE RN BETWEEN ? AND ?;
--Ű����˻�??(email,ename)
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM MEMBER ORDER BY MNAME)A) WHERE MEMAIL LIKE '%'||?||'%' OR MNAME LIKE'%'||?||'%' AND RN BETWEEN ? AND ?;
--��й�ȣã��??
SELECT * FROM MEMBER WHERE MEMAIL = ? AND MNAME = ?;


-----------------------------------------------------------
select * from PAYMENT where memail ='aa@11';
commit;

--�Ŀ�������
INSERT INTO SETPAY VALUES(1,1,'������Ű��',10000,'�Ŀ� ���� �� �⺻��ǰ���??');

--�Ŀ��� ����Ǵ�?? ������
INSERT INTO GETPROJECT VALUES(1,'test',1,10000);

--�Ŀ��� Ȯ��
SELECT A.*,PNAME,PEXP FROM GETPROJECT A, SETPAY B WHERE A.PAY = B.PAY AND A.PNO = 1 AND GNO = 1;


--
INSERT INTO PAYMENT VALUES('CARDNUM','12','23','2332323',21,'123','4567','8901','aa@11');

UPDATE PAYMENT SET PCNUM=?,PMONTH=?,PYEAR=?,PBIRTH=?,PPW=?,PPHONE1=?,PPHONE2=?,PPHONE3=? WHERE MEMAIL=?;
commit;
UPDATE PAYMENT SET PCNUM=?,PMONTH=?,PYEAR=?,PBIRTH=?,PPW=?,PPHONE1=?,PPHONE2=?,PPHONE3=? WHERE MEMAIL=?;
SELECT * FROM PAYMENT; 
DELETE FROM PAYMENT WHERE PCNUM='1232-3232-2222-2222';



------------------------------------------------------------
--project���?
INSERT INTO PROJECT (PNO,PTITLE,PDATE,MEMAIL,PPAY,PCONTENT,PIMAGE,PCATEGORY,PACCOUNT,PBANKNAME,PACNAME)VALUES(PROJECT_SEQ.NEXTVAL,'123',?,?,?,?,?,?,?,?,?);

--��ȸ������
UPDATE PROJECT SET PCNT=PCNT+1 WHERE PNO=10;
--�Ŀ���û�� �Ŀ�������
UPDATE PROJECT SET PNOW=PNOW+2000 WHERE PNO=1;
--PROJECT����
UPDATE PROJECT SET PCONTENT = 'CONTENT',PACCOUNT = '����',PBANKNAME = '�����?' ,PACNAME = '������' WHERE PNO=1;
--����¡,5�����?(��ü��½�? ���?)
SELECT * FROM (SELECT ROWNUM RN, A.* FROM(SELECT * FROM PROJECT ORDER BY PNO)A)WHERE RN BETWEEN ? AND ?;
--ī�װ� ���� ��ȸ�� TOP 3 ���?
SELECT * FROM (SELECT ROWNUM RN, A.* FROM(SELECT * FROM PROJECT ORDER BY PCNT)A)WHERE PCATEGORY=? AND RN BETWEEN ? AND ?;
-- ����
DELETE FROM PROJECT WHERE PNO=1;
-- PPAY, PNOW ��������
SELECT PPAY,PNOW FROM PROJECT WHERE PNO=1;
--���� �ø� ������Ʈ
SELECT * FROM (SELECT ROWNUM RN, A.* FROM(SELECT * FROM PROJECT ORDER BY PCNT)A)WHERE MEMAIL='?' AND RN BETWEEN ? AND ?;
--���Ǻ� �˻�
SELECT * FROM (SELECT ROWNUM RN, A.* FROM(SELECT * FROM PROJECT ORDER BY PTITLE)A)WHERE MEMAIL LIKE '%'||?||'%' OR PTITLE LIKE '%'||?||'%' AND RN BETWEEN ? AND ?;
--������������
SELECT * FROM PROJECT WHERE PNO=?;
SELECT * FROM PROJECT;

commit;
SELECT * FROM (SELECT ROWNUM RN, A.* FROM(SELECT * FROM PROJECT ORDER BY PCNT DESC)A)WHERE RN BETWEEN 1 AND 3;



--------------------------------------------------------------------------
--���� ����
INSERT INTO BOARD (BNO,MEMAIL,BTITLE,BCONTENT,BIMAGE,BGROUP,BIP)VALUES(BOARD_SEQ.NEXTVAL,'test@test','TITLE','CONTENT','Desert.jpg',BOARD_SEQ.CURRVAL,'1.1.1.1');

--��ü ����
SELECT COUNT(*) FROM BOARD;
--��ü�ҷ�����
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT *FROM BOARD ORDER BY BGROUP DESC,BSTEP)A) WHERE RN BETWEEN 1 AND 5;

--�ϳ� ã�ƿ���
SELECT * FROM BOARD WHERE BNO = 10;

--�˻����?(TITLE)
SELECT * FROM BOARD WHERE BTITLE LIKE '%'||?||'%' ;
--�˻����?(MEMAIL)
SELECT * FROM BOARD WHERE MEMAIL LIKE '%'||?||'%';

--����
UPDATE BOARD SET BTITLE = '����',BCONTENT='����',BIMAGE='Penguins.jsp' WHERE BNO = 10;

--��ȸ�� ����
UPDATE BOARD SET BHIT = BHIT+1 WHERE BNO=10;

--�� �����ϱ�
DELETE FROM BOARD WHERE BNO=11;
SELECT * FROM BOARD;
--��۾���?
UPDATE BOARD SET BSTEP = BSTEP+1
    WHERE BGROUP = 10 AND BSTEP>0;
INSERT INTO BOARD (BNO,MEMAIL,BTITLE,BCONTENT,BIMAGE,BGROUP,BIP,BSTEP,BINDENT)VALUES(BOARD_SEQ.NEXTVAL,'test@test','TITLE','CONTENT','Desert.jpg',10,'1.1.1.1',1,1);

SELECT * FROM BOARD;
SELECT * FROM (SELECT ROWNUM RN, A.* FROM (SELECT * FROM BOARD WHERE BTITLE LIKE '%'||'t'||'%' ORDER BY BGROUP DESC,BSTEP)A)WHERE RN BETWEEN 1 AND 3;
SELECT B.* FROM MEMBER A, PAYMENT B WHERE A.MEMAIL=B.MEMAIL AND A.MEMAIL='test@test';
commit;
SELECT * FROM MEMBER WHERE MEMAIL='test@test';

commit;
SELECT * FROM SETPAY;
DELETE from setpay where spno=3;
SELECT COUNT(*) FROM SETPAY WHERE PNO=?;
--------------setpay
INSERT INTO SETPAY VALUES(SETPAY_SEQ.NEXTVAL,?,?,?,?);


--------------GETPROJECT
INSERT INTO GETPROJECT VALUES(GETPROJECT_SEQ.NEXTVAL,'test@test',1,10000);
SELECT * FROM GETPROJECT WHERE PNO=? AND MEMAIL=?;
UPDATE GETPROJECT SET PAY= ? WHERE PNO=? AND MEMAIL=?;

-----

SELECT * FROM (SELECT ROWNUM RN, A.* FROM(SELECT * FROM PROJECT ORDER BY PCNT DESC)A)WHERE PDATE > SYSDATE AND RN BETWEEN 1 AND 3;
SELECT P.*,A.GNO,A.PAY FROM PROJECT P,(SELECT ROWNUM RN, G.* FROM MEMBER M , GETPROJECT G WHERE M.MEMAIL = G.MEMAIL AND G.MEMAIL='test@test' ORDER BY PNO) A WHERE A.PNO = P.PNO;
select * from getproject where gno=7;

DELETE FROM GETPROJECT WHERE GNO=6;


--check admin
INSERT INTO ADMIN VALUES('admin@admin','admin');
commit;
SELECT * FROM ADMIN WHERE AID ='ADMIN' AND APW='ADMIN' ;

